

apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc
  labels:
    app: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
      - name: discountgrpc
        image: discountgrpc
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: DatabaseSettings__ConnectionString
            value: Server=postgresdb-service;Port=8017;Database=admin;User Id=admin;Password=admin1234;

---

apiVersion: v1
kind: Service
metadata:
  name: discountgrpc-service
spec:
  type: NodePort
  selector:
    app: discountgrpc
  ports:
    - port: 8028
      targetPort: 80