apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi
  labels:
    app: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogapi
  template:
    metadata:
      labels:
        app: catalogapi
    spec:
      containers:
      - name: catalogapi
        image: catalogapi
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: DatabaseSettings__ConnectionString
            value: mongodb://mongodb-service:31012

---

apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  type: NodePort
  selector:
    app: catalogapi
  ports:
    - port: 8007
      targetPort: 80
      nodePort: 32000


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - port: 8017
      targetPort: 27017
      nodePort: 31012