apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
  labels:
    app: redisdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisdb
  template:
    metadata:
      labels:
        app: redisdb
    spec:
      containers:
      - name: redisdb
        image: redis
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redisdb-service
spec:
  type: NodePort
  selector:
    app: redisdb
  ports:
    - port: 8022
      targetPort: 6379
      nodePort: 30001


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi
  labels:
    app: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
      - name: basketapi
        image: basketapi
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: CacheSettings__ConnectionString
            value: redisdb-service:8022
          - name: GrpcSettings__DiscountUrl
            value: http://discountgrpc-service:8028
          - name: EventBusSettings__HostAddress
            value: amqp://guest:guest@rabbitmq-service:5672
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch-service:9200
          - name: OpenTelemetryTracingConfiguration__ZipkinUri
            value: http://zipkin-service:9411/api/v2/spans
          - name: OpenTelemetryTracingConfiguration__JaegerHost
            value: jaeger-service

---

apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  type: NodePort
  selector:
    app: basketapi
  ports:
    - port: 8008
      targetPort: 80
      nodePort: 32001