apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountapi
  labels:
    app: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountapi
  template:
    metadata:
      labels:
        app: discountapi
    spec:
      containers:
      - name: discountapi
        image: discountapi
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: DatabaseSettings__ConnectionString
            value: Server=postgresdb-service;Port=8017;Database=admin;User Id=admin;Password=admin1234;
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch-service:9200

---

apiVersion: v1
kind: Service
metadata:
  name: discountapi-service
spec:
  type: NodePort
  selector:
    app: discountapi
  ports:
    - port: 8018
      targetPort: 80
      nodePort: 32019