
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi
  labels:
    app: orderingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderingapi
  template:
    metadata:
      labels:
        app: orderingapi
    spec:
      containers:
      - name: orderingapi
        image: orderingapi
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ConnectionStrings__OrderingConnectionString
            value: Server=mssqlorderdb-service,1433;Database=OrderDb;Trusted_Connection=false;User Id=sa;Password=MyC0m9l&xP@ssw0rd
          - name: EventBusSettings__HostAddress
            value: amqp://guest:guest@rabbitmq-service:5672
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch-service:9200

---

apiVersion: v1
kind: Service
metadata:
  name: orderingapi-service
spec:
  type: NodePort
  selector:
    app: orderingapi
  ports:
    - port: 8100
      targetPort: 80
      nodePort: 32200
