
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingaggregator
  labels:
    app: shoppingaggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shoppingaggregator
  template:
    metadata:
      labels:
        app: shoppingaggregator
    spec:
      containers:
      - name: shoppingaggregator
        image: shoppingaggregator
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ApiSettings__CatalogUrl
            value: http://catalogapi-service:8007
          - name: ApiSettings__BasketUrl
            value: http://basketapi-service:8008
          - name: ApiSettings__OrderingUrl
            value: http://orderingapi-service:8100
          - name: ElasticConfiguration__Uri
            value: http://elasticsearch-service:9200
          - name: OpenTelemetryTracingConfiguration__ZipkinUri
            value: http://zipkin-service:9411/api/v2/spans
          - name: OpenTelemetryTracingConfiguration__JaegerHost
            value: jaeger-service

---

apiVersion: v1
kind: Service
metadata:
  name: shoppingaggregator-service
spec:
  type: NodePort
  selector:
    app: shoppingaggregator
  ports:
    - port: 8008
      targetPort: 80
      nodePort: 32021