
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one
        ports:
        - containerPort: 80
        - containerPort: 6831
        - containerPort: 16686

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - port: 8025
      targetPort: 80
      name: jaegerpod
      nodePort: 32029
    - port: 6831
      targetPort: 6831
      name: jaegerpodport
    - port: 16686
      targetPort: 16686
      name: jaegerweb
      nodePort: 32031