
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webstatus
  labels:
    app: webstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webstatus
  template:
    metadata:
      labels:
        app: webstatus
    spec:
      containers:
      - name: webstatus
        image: webstatus
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
          - name: environmentVariables__ASPNETCORE_ENVIRONMENT
            value: Development
          - name: HealthChecksUI__HealthChecks__0__Name
            value: Catalog Health Check
          - name: HealthChecksUI__HealthChecks__0__Uri
            value: http://catalogapi-service:8007/hc
          - name: HealthChecksUI__HealthChecks__1__Name
            value: Basket Health Check
          - name: HealthChecksUI__HealthChecks__1__Uri
            value: http://basketapi-service:8008/hc
          - name: HealthChecksUI__HealthChecks__2__Name
            value: Discount Health Check
          - name: HealthChecksUI__HealthChecks__2__Uri
            value: http://discountapi-service:8018/hc
          - name: HealthChecksUI__HealthChecks__3__Name
            value: Ordering Health Check
          - name: HealthChecksUI__HealthChecks__3__Uri
            value: http://orderingapi-service:8100/hc
          - name: HealthChecksUI__HealthChecks__4__Name
            value: Shopping Aggregator Health Check
          - name: HealthChecksUI__HealthChecks__4__Uri
            value: http://shoppingaggregator-service:8008/hc

---

apiVersion: v1
kind: Service
metadata:
  name: webstatus-service
spec:
  type: NodePort
  selector:
    app: webstatus
  ports:
    - port: 8103
      targetPort: 80
      nodePort: 32301
